### ISSUE TITLE
Opening files causes `Watchdog error: Got unknown document URI`

### ISSUE THREAD

**Issue by tydeu** [leanprover-community/vscode-lean4#21]
On `vscode-lean4` v0.0.23, when opening a file from the File Explorer (or with by following a link), the server dies with the following bug messages multiple times until it stops restarting. However, this does not happen when switching between open tabs.

```
Watchdog error: Got unknown document URI (file:///<foo.lean>)
[Error - <time>] Connection to server got closed. Server will not be restarted.
[Error - <time>] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (<home>\.vscode\extensions\leanprover.lean4-0.0.23\out\extension.js:2:145554)
	at Object.dispose (<home>\.vscode\extensions\leanprover.lean4-0.0.23\out\extension.js:2:225726)
	at C.handleConnectionClosed (<home>\.vscode\extensions\leanprover.lean4-0.0.23\out\extension.js:2:225939)
	at C.handleConnectionClosed (<home>\.vscode\extensions\leanprover.lean4-0.0.23\out\extension.js:2:286327)
	at t (<home>\.vscode\extensions\leanprover.lean4-0.0.23\out\extension.js:2:224028)
	at invoke (<home>\.vscode\extensions\leanprover.lean4-0.0.23\out\extension.js:2:147167)
	at o.fire (<home>\.vscode\extensions\leanprover.lean4-0.0.23\out\extension.js:2:147928)
	at Y (<home>\.vscode\extensions\leanprover.lean4-0.0.23\out\extension.js:2:134812)
	at invoke (<home>\.vscode\extensions\leanprover.lean4-0.0.23\out\extension.js:2:147167)
	at o.fire (<home>\.vscode\extensions\leanprover.lean4-0.0.23\out\extension.js:2:147928)
	at g.fireClose (<home>\.vscode\extensions\leanprover.lean4-0.0.23\out\extension.js:2:155809)
	at Socket.<anonymous> (<home>\.vscode\extensions\leanprover.lean4-0.0.23\out\extension.js:2:157394)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:674:12)
```

The file `foo.lean` is the file that was just open (and is thus a valid file). After manually restarting the server with the command `Lean 4: Restart server` everything works fine until I open another file.

**Comment by Kha** [comment]
This should have been fixed in the server about a month ago. What version of Lean 4 are you using?

**Comment by tydeu** [comment]
I'm running `Lean 4.0.0-m2`. So this is an issue with Lean 4 itself? I kind of assumed the problems in VS Code would come from the extension not from Lean itself (as everything builds fine).

**Comment by mhuisi** [comment]
> I'm running `Lean 4.0.0-m2`. So this is an issue with Lean 4 itself? I kind of assumed the problems in VS Code would come from the extension and not from Lean itself (as everything builds fine).

vscode-lean4 targets the nightly builds of Lean 4: https://github.com/leanprover-community/vscode-lean4#running-the-client

**Comment by Kha** [comment]
> I kind of assumed the problems in VS Code would come from the extension and not from Lean itself (as everything builds fine).

The language server is part of Lean 4, not of the editor extension

**Comment by tydeu** [comment]
Whelp, my bad. Thanks for setting me straight!
